<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SCDC.Api</RootNamespace>
    <AssemblyName>SCDC.Api</AssemblyName>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SCDC.BuildingBlocks/SCDC.BuildingBlocks.csproj" />
    <ProjectReference Include="../SCDC.Contracts/SCDC.Contracts.csproj" />
    <ProjectReference Include="../Modules/Identity/SCDC.Identity.csproj" />
    <ProjectReference Include="../Modules/Community/SCDC.Community.csproj" />
    <ProjectReference Include="../Modules/Messaging/SCDC.Messaging.csproj" />
  </ItemGroup>

</Project>
