<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SCDC.BuildingBlocks</RootNamespace>
    <AssemblyName>SCDC.BuildingBlocks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <ProjectReference Include="../SCDC.Contracts/SCDC.Contracts.csproj" />
  </ItemGroup>

</Project>
