<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SCDC.BuildingBlocks</RootNamespace>
    <AssemblyName>SCDC.BuildingBlocks</AssemblyName>
  </PropertyGroup>

</Project>
